server:
  port: ${PORT:8080}

spring:
  application:
    name: todo-api

  datasource:
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
    show-sql: false

  sql:
    init:
      mode: NEVER

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_GMAIL_USERNAME}
    password: ${DEV_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration:
    auth: 300 # 5 minutes TODO: parameterize
    passwordReset: 900 # 15 minutes TODO: parameterize
    refresh: 86_400 # 24 hours TODO: parameterize
    cookie: 1_800 # 30 minutes TODO: parameterize
  prefix: Bearer
  header: Authorization

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %c{1} -%replace( [%X{request_id}]){' \\[\\]', ''} %msg%n"
  # level:
  #   org:
  #     springframework:
  #       security: debug
  #       web:
  #         filter:
  #           CommonsRequestLoggingFilter: debug
  #     hibernate:
  #       SQL: debug
  #       type:
  #         descriptor:
  #           sql:
  #             BasicBinder: trace
